#!/bin/bash

## This script will deploy puppet and its dependencies in a debian environment


## Must run as root
(( UID )) && { echo >&2 "Permission denied. Are you root?"; exit 1;  }

apt-get update
apt-get install puppet puppetmaster facter rubygems
gem install puppet-module
