#!/bin/bash

cd  vm

qemu-system-arm  \
  -kernel kernel \
  -cpu arm1176   \
  -m 256         \
  -M versatilepb \
  -name Coffeebot \
  -no-reboot     \
  -serial stdio  \
  -append "root=/dev/sda2 panic=1" \
  -hda vm.img    \
  -redir tcp:5022::22 \
  -rtc base="localtime"
